# Spring Profiles
spring.profiles.active=prod

# Spring application api path
spring.config.import=optional:classpath:application-API-KEY.properties,optional:classpath:application-prod.yml

# Spring Application Name
spring.application.name=back

# H2 Database Settings
spring.datasource.url=jdbc:h2:mem:didimdb;MODE=MySQL;NON_KEYWORDS=USER
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# JWT Settings (Custom)
jwt.secret=vmlzdWFsc3R1ZGlvY29kZWdlbWluaWNsY2Fwc3RvbmVwcm9qZWN0c2VjcmV0a2V5MjAyNDA2MDY=
jwt.expiration=86400000

# File Upload Settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# AI Analysis Server (FastAPI)
ai.server.url=http://127.0.0.1:8000

# Logging
logging.level.com.capstone.back=DEBUG
